# -*- coding: utf-8 -*-
"""RAG

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14keQa-ew360fVLSDs9Ikia9wM6mmva9M
"""

!pip install -q pymupdf
!pip install -q sentence-transformers
!pip install -q scikit-learn
!pip install -q langchain
!pip install -q langchain-community

import fitz
import numpy as np
import pandas as pd

from sentence_transformers import SentenceTransformer

from sklearn.metrics.pairwise import cosine_similarity

from langchain_text_splitters import RecursiveCharacterTextSplitter

import re
import fitz
import numpy as np
import pandas as pd

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from langchain_text_splitters import RecursiveCharacterTextSplitter

pdf = fitz.open("Panduan Akademik Statistika.pdf.pdf")

print("Jumlah halaman :", len(pdf))

def clean_text(text):


    text = re.sub(
        r"Buku Panduan Akademik.*?Kurikulum 2022",
        "",
        text,
        flags=re.IGNORECASE
    )


    text = re.sub(
        r"\b(i|ii|iii|iv|v|vi|vii|viii|ix|x)\b",
        "",
        text,
        flags=re.IGNORECASE
    )


    text = re.sub(r"\n\s*\d+\s*\n", "\n", text)


    text = re.sub(r"\n{2,}", "\n", text)


    text = re.sub(r"[ \t]+", " ", text)

    return text.strip()

splitter = RecursiveCharacterTextSplitter(

    chunk_size=250,
    chunk_overlap=50,

    separators=[
        "\n\n",
        "\n",
        ". ",
        ";",
        ",",
        " "
    ]
)

chunks = []

for page_num, page in enumerate(pdf):

    text = clean_text(page.get_text("text"))

    hasil_split = splitter.split_text(text)

    for chunk in hasil_split:

        chunk = chunk.strip()

        if len(chunk) < 50:
            continue


        if re.search(r"\.{5,}", chunk):
            continue


        if chunk.lower().startswith("daftar tabel"):
            continue


        if chunk.lower().startswith("daftar gambar"):
            continue


        if chunk.lower().startswith("daftar isi"):
            continue

        chunks.append({

            "page": page_num + 1,

            "text": chunk

        })

print("Jumlah Chunk :", len(chunks))

"""Pembuatan Embanding"""

from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer(
    "intfloat/multilingual-e5-base"
)

embeddings = embedding_model.encode(
    ["passage: " + chunk["text"] for chunk in chunks],
    normalize_embeddings=True,
    convert_to_tensor=False,
    show_progress_bar=True
)

assert len(chunks) == len(embeddings)

print(len(chunks))
print(len(embeddings))

def retrieve(question, top_k=3):

    query_embedding = embedding_model.encode(
        "query: " + question,
        normalize_embeddings=True,
        convert_to_tensor=False
    ).astype("float32")

    scores, indices = index.search(
        np.array([query_embedding]),
        top_k
    )

    results = []

    for score, idx in zip(scores[0], indices[0]):

        results.append({
            "page": chunks[idx]["page"],
            "score": float(score),
            "text": chunks[idx]["text"]
        })

    return results

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

def semantic_search(question, top_k=5):

    query_embedding = embedding_model.encode(
        "query: " + question,
        normalize_embeddings=True,
        convert_to_tensor=False
    )

    similarity = cosine_similarity(
        [query_embedding],
        embeddings
    )[0]

    ranking = np.argsort(similarity)[::-1][:top_k]

    hasil = []

    for idx in ranking:

        hasil.append({

            "page": chunks[idx]["page"],

            "score": float(similarity[idx]),

            "text": chunks[idx]["text"]

        })

    return hasil

question = "Apa syarat cuti akademik?"

hasil = semantic_search(question, top_k=5)

print("PERTANYAAN :", question)

for i, h in enumerate(hasil, 1):

    print("="*60)

    print("Rank :", i)

    print("Halaman :", h["page"])

    print("Similarity :", round(h["score"],4))

    print(h["text"])

"""Nomor 5"""

!pip install -q faiss-cpu
!pip install -q langchain-google-genai
!pip install -q gradio

import faiss
import gradio as gr

from google.colab import userdata

from langchain_google_genai import ChatGoogleGenerativeAI

GOOGLE_API_KEY = userdata.get("GOOGLE_API_KEY")

llm = ChatGoogleGenerativeAI(
    model="gemini-3.1-flash-lite",
    temperature=0,
    google_api_key=GOOGLE_API_KEY
)

embeddings = np.array(embeddings).astype("float32")

dimension = embeddings.shape[1]

index = faiss.IndexFlatIP(dimension)

index.add(embeddings)

print(index.ntotal)

docs = retrieve("Apa syarat kelulusan?")

for i, doc in enumerate(docs):

    print("="*80)

    print("Rank :", i+1)

    print("Page :", doc["page"])

    print("Similarity :", doc["score"])

    print(doc["text"][:500])

docs = retrieve("Apa syarat kelulusan?")

context = "\n\n".join(doc["text"] for doc in docs)

prompt = f"""
Konteks:

{context}

Pertanyaan:

Apa syarat kelulusan?

Jawaban:
"""

response = llm.invoke(prompt)

print(response)

import faiss
import numpy as np

embeddings = np.array(embeddings).astype("float32")

dimension = embeddings.shape[1]

index = faiss.IndexFlatIP(dimension)

index.add(embeddings)

print("Jumlah dokumen:", index.ntotal)

def retrieve(question, top_k=3):

    query_embedding = embedding_model.encode(
        "query: " + question,
        normalize_embeddings=True,
        convert_to_tensor=False
    ).astype("float32")

    scores, indices = index.search(
        np.array([query_embedding]),
        top_k
    )

    docs = []

    for score, idx in zip(scores[0], indices[0]):

        docs.append({

            "page": chunks[idx]["page"],

            "score": float(score),

            "text": chunks[idx]["text"]

        })

    return docs

import gradio as gr

import gradio as gr

def chatbot(question):

    docs = retrieve(question)

    context = "\n\n".join(
        doc["text"] for doc in docs
    )

    prompt = f"""
Kamu adalah chatbot akademik Program Studi Statistika Universitas Islam Indonesia.

Jawablah pertanyaan HANYA berdasarkan konteks berikut.

Jika jawaban tidak ditemukan pada konteks, katakan:

"Informasi tidak ditemukan pada dokumen."

====================
KONTEKS
====================

{context}

====================
PERTANYAAN
====================

{question}

====================
JAWABAN
====================
"""

    try:

        response = llm.invoke(prompt)

        if isinstance(response.content, list):

            answer = ""

            for item in response.content:

                if isinstance(item, dict):

                    answer += item.get("text", "")

        else:

            answer = str(response.content)

    except Exception as e:

        answer = f"Terjadi kesalahan:\n\n{e}"

    references = "\n".join(

        f"• Halaman {doc['page']} | Similarity : {doc['score']:.4f}"

        for doc in docs

    )

    return f"""
# 📌 Jawaban

{answer}

---

# 📖 Referensi

{references}
"""

demo = gr.Interface(
    fn=chatbot,

    inputs=gr.Textbox(
        lines=2,
        label="Pertanyaan",
        placeholder="Contoh: Apa visi Program Studi Statistika?"
    ),

    outputs=gr.Markdown(),

    title="📘 Chatbot Buku Panduan Akademik",

    description="""
Retrieval-Augmented Generation (RAG)

📄 Dokumen : Buku Panduan Akademik Program Studi Statistika UII

🧠 Embedding : intfloat/multilingual-e5-base

🗂️ Vector Database : FAISS

🤖 LLM : gemini-2.5-pro
"""
)

def chatbot(question):

    docs = retrieve(question)

    context = "\n\n".join(
        doc["text"] for doc in docs
    )

    prompt = f"""
Kamu adalah chatbot akademik Program Studi Statistika Universitas Islam Indonesia.

Jawablah pertanyaan HANYA berdasarkan konteks berikut.

Jika jawaban tidak ditemukan pada konteks, katakan:

"Informasi tidak ditemukan pada dokumen."

====================
KONTEKS
====================

{context}

====================
PERTANYAAN
====================

{question}

====================
JAWABAN
====================
"""

    try:

        response = llm.invoke(prompt)

        if isinstance(response.content, list):

            answer = ""

            for item in response.content:

                if isinstance(item, dict):

                    answer += item.get("text", "")

        else:

            answer = str(response.content)

    except Exception as e:

        answer = f"Terjadi kesalahan:\n\n{e}"

    references = "\n".join(

        f"• Halaman {doc['page']} | Similarity : {doc['score']:.4f}"

        for doc in docs

    )

    return f"""
# 📌 Jawaban

{answer}

---

# 📖 Referensi

{references}
"""

import faiss

faiss.write_index(index, "index.faiss")

import pickle

with open("chunks.pkl", "wb") as f:
    pickle.dump(chunks, f)

import numpy as np

np.save("embeddings.npy", embeddings)

demo.launch(
    share=True,
    debug=True
)